"""Immutable, versioned messages at every ViabilityGrid component boundary."""

from cmw.contracts._base import CURRENT_SCHEMA_VERSION
from cmw.contracts.codec import decode_contract, encode_contract
from cmw.contracts.models import (
    CONTRACT_TYPES,
    ActionDecision,
    ActionProposal,
    AppraisalVector,
    BeliefState,
    ComputeAllocation,
    Contract,
    EligibilityEntry,
    ErrorBundle,
    ExperienceTrace,
    FeatureValue,
    ObservationEnvelope,
    PlasticitySchedule,
    PredictedOutcome,
    PredictionDistribution,
    ProcessingPriority,
    Provenance,
    RationaleComponent,
    ReferencePoint,
    ReferenceTrajectory,
    ReliabilityEstimate,
    ResourceBudget,
    ResourceCost,
    SelfEstimate,
    StateHypothesis,
    Uncertainty,
    WorkspaceEntry,
    WorkspaceState,
)

__all__ = [
    "CONTRACT_TYPES",
    "CURRENT_SCHEMA_VERSION",
    "ActionDecision",
    "ActionProposal",
    "AppraisalVector",
    "BeliefState",
    "ComputeAllocation",
    "Contract",
    "EligibilityEntry",
    "ErrorBundle",
    "ExperienceTrace",
    "FeatureValue",
    "ObservationEnvelope",
    "PlasticitySchedule",
    "PredictedOutcome",
    "PredictionDistribution",
    "ProcessingPriority",
    "Provenance",
    "RationaleComponent",
    "ReferencePoint",
    "ReferenceTrajectory",
    "ReliabilityEstimate",
    "ResourceBudget",
    "ResourceCost",
    "SelfEstimate",
    "StateHypothesis",
    "Uncertainty",
    "WorkspaceEntry",
    "WorkspaceState",
    "decode_contract",
    "encode_contract",
]
